//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyRecord
    {
        public int RecordID { get; set; }
        public Nullable<int> EmpId { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Experience { get; set; }
        public string Designation { get; set; }
    
        public virtual EmployeeDetail EmployeeDetail { get; set; }
    }
}
